# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_ROCKCHIP_CIF) += rockchip-cif.o
rockchip-cif-objs += rkcif-dev.o \
	rkcif-capture-dvp.o \
	rkcif-capture-mipi.o \
	rkcif-interface.o \
	rkcif-stream.o
